#!/usr/bin/env bash
realm=$1
if [[ -z "$realm" ]]; then
    echo "Must provide realm to ensure ticket"
    exit 1
fi

ticket=$(klist 2>/dev/null | grep "krbtgt/${realm}@${realm}" )
if [[ -z "$ticket" ]]; then
    kinit ${USER}@${realm}
    exit $?
else
    os_type=$(uname)
    if [[ $os_type == "Darwin" ]]; then
        expires=$(echo "$ticket" | cut -d ' ' -f 6-9 )
        expires_epoch=$(date -j -f "%b %d %H:%M:%S %Y" "$expires" +"%s")
        now_epoch=$(date +"%s")
    #    echo "expires: $expires_epoch  now: $now_epoch"
    elif [[ $os_type == "Linux" ]]; then
        expires=$(echo "$ticket" | cut -d ' ' -f 4-5 )
        expires_epoch=$(date -d "$expires" +"%s")
        now_epoch=$(date +"%s")
    else
        echo "Can't determine OS type from 'uname'"
        exit 2
    fi
    if [[ $expires_epoch < $now_epoch ]]; then
        kinit ${USER}@${realm}
        exit $?
    fi
    exit 0
fi
